backend:
  name: github
  repo: joernba/grafica-gioia # Path to your Github repository
  branch: master # Branch to update (master by default)

media_folder: "_dev/_src/images/pages/uploads" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: "pages" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Pages" # Used in the UI, ie.: "New Post"
    folder: "_pages" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Indicator", name: "indicator", widget: "string"}
      - {label: "Quote", name: "quote", widget: "string"}
      - {label: "Quote Author", name: "quote-author", widget: "string"}
      - {label: "Color", name: "color", widget: "hidden"}
#       - {label: "Images", name: "images", widget: "image", required: false}
      - {label: "Permalink", name: "permalink", widget: "hidden"}
      - {label: "Layout", name: "layout", widget: "hidden"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
